version: "3"
services:
  frontend:
    container_name: frontend_app
    build: .
    ports:
      - "7500:7500"
    networks:
      - nodenw
    links:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27018:27017"
    networks:
      - nodenw
    volumes:
      - nodevolumes:/data/db
volumes:
  nodevolumes:
networks:
  nodenw:
    driver: "bridge"